using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyConfigurationAttribute("net-4.0.win32; release")]
[assembly: AssemblyProductAttribute("Quarz.NET 2.3.3 for .NET 4.0")]
[assembly: AssemblyDescriptionAttribute("Quartz Scheduling Framework for .NET")]
[assembly: AssemblyCopyrightAttribute("Copyright 2001-2014 Marko Lahma")]
[assembly: AssemblyTrademarkAttribute("Apache License, Version 2.0")]
[assembly: AssemblyCompanyAttribute("http://www.quartz-scheduler.net/")]
[assembly: AssemblyCultureAttribute("")]
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyVersionAttribute("2.3.3.0")]
[assembly: AssemblyInformationalVersionAttribute("2.3.3.56 / 0f171ed4ef01333e7353c5a4230586018bd25765")]
[assembly: AssemblyDelaySignAttribute(false)]

